In [1]:
!pip install numpy

In [2]:
import numpy as np


#create array usin numpy
#create 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [4]:
np.arange(0,10,1).reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
#numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# ADDITION 
print("ADDITION ", arr1+arr2)

#substraction
print("subtraction ", arr1-arr2)

#multplication
print("multiplication ", arr1*arr2)

#division
print("division ", arr1/arr2)

ADDITION  [11 22 33 44 55]
subtraction  [ -9 -18 -27 -36 -45]
multiplication  [ 10  40  90 160 250]
division  [0.1 0.1 0.1 0.1 0.1]


In [8]:
#universal function

arr = np.array([1,2,3,4,5])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))



[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [9]:
#array slicilng and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("array\n", arr)

array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(arr[1][3])
print(arr[0:3,2:3])

8
[[ 3]
 [ 7]
 [11]]


In [11]:
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [12]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [13]:
## statical concept--normalization

data=np.array([1,2,3,4,5])

#mean and standard deviation

mean = np.mean(data)
std_dev = np.std(data)

normalising_data =( data-mean)/std_dev

print("normalised data\n", normalising_data)

normalised data
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
